name: Builds

on: [push, pull_request]

jobs:
  build:
    name: Build on MacOS
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4
        with:
          path: MITK

      - name: Add ccache
        uses: hendrikmuhs/ccache-action@v1.2

      - name: Install tools
        run: brew install tree doxygen libomp

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          aqtversion: '==3.1.*'
          version: 6.7.3
          host: mac
          target: desktop
          arch: clang_64
          modules: 'qt3d qtcharts qtconnectivity qtdatavis3d qtgraphs qtgrpc qthttpserver qtimageformats qtlanguageserver qtlocation qtlottie qtmultimedia qtnetworkauth qtpdf qtpositioning qtquick3dphysics qtquickeffectmaker qtremoteobjects qtscxml qtsensors qtserialbus qtserialport qtspeech qtvirtualkeyboard qtwebchannel qtwebengine qtwebsockets qtwebview qt5compat qtquick3d qtquicktimeline qtshadertools'
          cache: 'true'

      - name: Build MITK
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.15
        run: |
          export OpenMP_ROOT=$(brew --prefix)/opt/libomp
          mkdir MITK-superbuild
          cd MITK-superbuild
          cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache ../MITK
          make -j4
          cd MITK-build
          make package

      - name: List binaries
        run: tree bin
      
      - name: Upload disk image
        uses: actions/upload-artifact@v4
        with:
          name: image-${{ matrix.os }}
          path: bin/*.dmg
