name: Builds

on: [push, pull_request]

jobs:
  build:
    name: Build on MacOS
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4
        with:
          path: MITK

      - name: Add ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}-macos-13
          max-size: "2000M"

      - name: Install tools
        run: brew install tree doxygen libomp

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          aqtversion: '==3.1.*'
          version: 5.15.*
          host: mac
          target: desktop
          arch: clang_64
          modules: 'debug_info qtcharts qtdatavis3d qtlottie qtnetworkauth qtpurchasing qtquick3d qtquicktimeline qtscript qtvirtualkeyboard qtwebengine qtwebglplugin'
          cache: 'true'

      - name: Build MITK
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.15
        run: |
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          export OpenMP_ROOT=$(brew --prefix)/opt/libomp
          mkdir MITK-superbuild
          cd MITK-superbuild
          cmake -D MITK_USE_CTK=OFF -D MITK_USE_Qt6=OFF -D CMAKE_BUILD_TYPE=Release -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache ../MITK
          make -j4
          cd MITK-build
          make package

      - name: List files
        run: tree .
      
      - name: Upload disk image
        uses: actions/upload-artifact@v4
        with:
          name: image-1015
          path: MITK-superbuild/MITK-build/*.dmg
